# Generated by Django 6.0.2 on 2026-03-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_customerreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_duplicate",
            field=models.BooleanField(
                default=False, help_text="Whether this product is a duplicate"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="master_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the master version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="shop.product",
            ),
        ),
    ]
